services:
  attest-ai:
    image: ghcr.io/mrgarbonzo/attest_ai:latest
    ports:
      - "9000:${API_PORT:-9000}"
    environment:
      - SECRET_AI_API_KEY=${SECRET_AI_API_KEY}
      - ARWEAVE_MNEMONIC=${ARWEAVE_MNEMONIC}
      - ARWEAVE_GATEWAY=${ARWEAVE_GATEWAY}
      - API_PORT=${API_PORT}
      - DEBUG=${DEBUG}
    restart: unless-stopped